# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Embedded/Nexys-A7/Nexys-A7/hw/src/ip/BRAM_1/BRAM_1.xci
# IP: The module: 'BRAM_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Embedded/Nexys-A7/Nexys-A7/hw/proj/hw.gen/sources_1/ip/BRAM_1/BRAM_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/Embedded/Nexys-A7/Nexys-A7/hw/src/ip/BRAM_1/BRAM_1.xci
# IP: The module: 'BRAM_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Embedded/Nexys-A7/Nexys-A7/hw/proj/hw.gen/sources_1/ip/BRAM_1/BRAM_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
