# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Embedded/Nexys-A7/Nexys-A7/hw/src/ip/ClkGen/ClkGen.xci
# IP: The module: 'ClkGen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Embedded/Nexys-A7/Nexys-A7/hw/proj/hw.gen/sources_1/ip/ClkGen/ClkGen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClkGen'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Embedded/Nexys-A7/Nexys-A7/hw/proj/hw.gen/sources_1/ip/ClkGen/ClkGen.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClkGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Embedded/Nexys-A7/Nexys-A7/hw/proj/hw.gen/sources_1/ip/ClkGen/ClkGen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClkGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/Embedded/Nexys-A7/Nexys-A7/hw/src/ip/ClkGen/ClkGen.xci
# IP: The module: 'ClkGen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Embedded/Nexys-A7/Nexys-A7/hw/proj/hw.gen/sources_1/ip/ClkGen/ClkGen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClkGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Embedded/Nexys-A7/Nexys-A7/hw/proj/hw.gen/sources_1/ip/ClkGen/ClkGen.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClkGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Embedded/Nexys-A7/Nexys-A7/hw/proj/hw.gen/sources_1/ip/ClkGen/ClkGen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClkGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
